# Generated by Django 4.2.11 on 2024-04-08 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['title'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
    ]
