FROM node:20.5.0-alpine3.18
RUN addgroup reactapp && adduser -S -G reactapp reactapp
USER reactapp
WORKDIR /app/
COPY --chown=reactapp package*.json .
RUN npm install
COPY --chown=reactapp . .
# EXPOSE 3000
CMD ["npm", "start"]