FROM python:3.9-alpine3.19
ENV PYTHONUNBUFFERED 1
RUN apk update \
    && apk add --no-cache gcc musl-dev postgresql-dev python3-dev libffi-dev \
    && pip install --upgrade pip
RUN addgroup userapp && adduser -S -G userapp userapp
WORKDIR /app/
COPY --chown=userapp requirements.txt /app/
RUN python -m pip install -r requirements.txt
COPY --chown=userapp . /app/
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]