# Generated by Django 4.2.11 on 2024-04-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
    ]
