# Generated by Django 4.2.11 on 2024-04-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titutlo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('technology', models.CharField(max_length=200, verbose_name='Tecnología')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
        ),
    ]
