version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: backend:1
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres